/**
 * Maps AI training spec entity names → actual Supabase tables and key columns.
 * Use this when writing queries, exports, or UI field bindings.
 */

export const AI_TRAINING_SCHEMA = {
  farmerProfile: {
    table: 'farmers',
    specName: 'Farmers',
    keyFields: {
      farmer_id: 'id',
      district: 'district',
      pincode: 'pincode_id → pincode_master.pincode',
      soil_type: 'farm_blocks.soil_type_id → crm_masters',
      irrigation_type: 'farm_blocks.irrigation_type_id → crm_masters',
      farming_style: 'farming_style',
      experience_level: 'experience_level',
      preferred_language: 'preferred_language',
      crops: 'farm_blocks.crop_type (via blocks)',
    },
  },
  cropBlock: {
    table: 'farm_blocks',
    specName: 'CropBlocks',
    keyFields: {
      crop_block_id: 'id',
      crop: 'crop_type',
      variety: 'variety_name',
      acreage: 'acreage_decimal',
      planting_date: 'planting_date',
      dap: 'computed from planting_date',
      growth_stage: 'growth_stage_id → crm_masters',
      expected_harvest: 'metadata.expected_harvest',
    },
  },
  fieldFinding: {
    table: 'crm_field_findings',
    specName: 'FieldFindings',
    keyFields: {
      finding_id: 'id',
      crop_block_id: 'block_id',
      finding_type: 'finding_type',
      severity: 'severity',
      symptoms: 'observations',
      affected_area: 'affected_area_pct',
      image_ids: 'photo_urls',
      weather_context: 'weather_context',
      diagnosed_by: 'agronomist_name',
      ai_prediction: 'ai_prediction',
      final_confirmed_issue: 'final_confirmed_issue',
    },
  },
  cropImage: {
    table: 'crop_images',
    specName: 'CropImages',
    keyFields: {
      image_id: 'id',
      crop: 'crop',
      dap: 'dap',
      symptoms: 'symptoms',
      gps_region: 'gps_region',
      weather: 'weather_snapshot_id → weather_snapshots',
      ai_prediction: 'ai_prediction',
      agronomist_confirmation: 'agronomist_label',
      severity: 'severity',
      review_status: 'review_status',
    },
  },
  fieldActivity: {
    table: 'cultivation_activities',
    specName: 'FieldActivities',
    keyFields: {
      activity_type: 'activity_type / activity_type_id',
      activity_date: 'applied_at',
      dap: 'dap',
      cost: 'cost_inr + labour_cost_inr + spray_cost_inr + ...',
      dosage: 'dosage_structured',
      products_used: 'products',
      labour_used: 'labour_used',
      outcome: 'outcome',
    },
  },
  recommendation: {
    table: 'recommendation_records',
    specName: 'Recommendations',
    keyFields: {
      recommendation_id: 'id',
      issue_type: 'issue_detected',
      recommendation_text: 'recommendation_text',
      product_cart: 'products',
      ai_generated: 'ai_session_id IS NOT NULL',
      human_corrected: 'metadata.correction',
      confidence_score: 'ai_advisory_sessions.confidence_score',
      applied_by_farmer: 'application_status',
    },
  },
  recommendationOutcome: {
    table: 'recommendation_records',
    specName: 'RecommendationOutcomes',
    note: 'Structured outcome fields on recommendation_records; training rows in ai_learning_samples',
    keyFields: {
      recommendation_id: 'id',
      outcome: 'outcome',
      recovery_days: 'recovery_days',
      farmer_feedback: 'farmer_outcome_feedback',
      agronomist_feedback: 'agronomist_outcome_feedback',
      issue_resolved: 'issue_resolved',
      roi_impact: 'metadata.roi_impact',
    },
    trainingTable: 'ai_learning_samples',
  },
  weather: {
    table: 'weather_snapshots',
    specName: 'WeatherData',
    keyFields: {
      rainfall: 'rainfall_mm',
      humidity: 'humidity_pct',
      temperature: 'temperature_c',
      soil_moisture: 'soil_moisture_pct',
      disease_outbreak_alerts: 'disease_alerts',
    },
    rulesTable: 'weather_rule_definitions',
  },
  escalationCorrection: {
    table: 'agronomist_escalations',
    specName: 'EscalationCorrections',
    note: 'Stage 2 will add ai_training_events as unified spine',
    keyFields: {
      ai_prediction: 'ai_advisory_sessions → probable_issue',
      employee_prediction: 'correction JSONB',
      agronomist_final: 'correction.correctDiagnosis',
      confidence_before: 'confidence_at_escalation',
      correction_reason: 'agronomist_notes',
    },
  },
  confidenceEngine: {
    table: 'ai_advisory_sessions',
    specName: 'AI Confidence Engine',
    keyFields: {
      confidence_score: 'confidence_score',
      confidence_band: 'confidence_band',
      auto_sent: 'auto_sent',
      human_reviewed: 'human_reviewed',
      corrected: 'corrected',
      escalation_required: 'escalation_recommended',
    },
  },
  trainingSpine: {
    table: 'ai_learning_samples',
    specName: 'AI Training Samples',
    note: 'Stage 2 adds ai_training_events for unified correction spine',
  },
} as const;

export type AiTrainingEntity = keyof typeof AI_TRAINING_SCHEMA;
