import type { CropKnowledgePackage } from '../types.js';

const GINGER_SAFETY_RULES = [
  {
    id: 'no_spray_heavy_rain',
    check: 'weather' as const,
    condition: 'heavy_rain_forecast',
    rejectReason: 'Do not spray within 24h of heavy rain forecast',
  },
  {
    id: 'no_fungicide_heat',
    check: 'weather' as const,
    condition: 'high_heat',
    rejectReason: 'Avoid foliar fungicide application during peak heat stress',
  },
  {
    id: 'phi_minimum_7d',
    check: 'phi_rei' as const,
    condition: 'harvest_within_7d',
    rejectReason: 'Harvest within 7 days — chemical options restricted by PHI',
  },
  {
    id: 'vegetative_only_systemic',
    check: 'crop_stage' as const,
    condition: 'early_germination',
    rejectReason: 'Germination stage — use only cultural/biological measures',
  },
];

const GINGER_MANAGEMENT: CropKnowledgePackage['managementRules'] = [
  {
    diseaseLabel: 'Pyricularia leaf blast',
    objectives: ['Stop lesion spread', 'Reduce humidity in canopy', 'Protect new leaves'],
    ipm: ['Scout weekly for spindle lesions on youngest leaves', 'Remove severely affected leaves if <10% plot'],
    cultural: ['Improve drainage between beds', 'Avoid overhead irrigation during humid periods'],
    nutrition: ['Balanced N — avoid excess nitrogen during humid weather'],
    biological: ['Consider Trichoderma soil drench on affected beds'],
    chemical: [
      { activeIngredientClass: 'Strobilurin (QoI)', notes: 'Preventive when humidity high; rotate MOA' },
      { activeIngredientClass: 'Triazole (DMI)', notes: 'Curative at early lesion stage; PHI check required' },
    ],
    monitoring: ['Re-check D7 for new lesions', 'D14 canopy health photo'],
  },
  {
    diseaseLabel: 'Rhizome rot / Pythium',
    objectives: ['Improve drainage', 'Reduce rhizome infection', 'Prevent spread to adjacent beds'],
    ipm: ['Inspect rhizome on pull — soft rot smell is confirmatory'],
    cultural: ['Raise bed height', 'Stop irrigation until soil surface dries', 'Remove infected rhizomes'],
    nutrition: ['Calcium + potassium to strengthen cell walls post-recovery'],
    biological: ['Trichoderma + Pseudomonas seed/rhizome treatment'],
    chemical: [
      { activeIngredientClass: 'Phosphonate', notes: 'Soil drench only; not foliar' },
      { activeIngredientClass: 'Copper (soil)', notes: 'Limited use; soil pH dependent' },
    ],
    monitoring: ['D3 soil moisture check', 'D7 rhizome re-inspection'],
  },
  {
    diseaseLabel: 'Thrips',
    objectives: ['Reduce silver streak damage', 'Protect new flush leaves'],
    ipm: ['Yellow sticky traps at bed edges', 'Check leaf underside for larvae'],
    cultural: ['Remove weed hosts around plot margin'],
    nutrition: ['Adequate potassium improves tolerance'],
    biological: ['Neem-based repellent on new flush'],
    chemical: [
      { activeIngredientClass: 'Spinosyn', notes: 'Target larval stage; evening application' },
      { activeIngredientClass: 'Neonicotinoid (soil)', notes: 'Last resort; bee-safe timing only' },
    ],
    monitoring: ['D5 leaf underside check', 'D10 trap count'],
  },
  {
    diseaseLabel: 'Nutrient deficiency',
    objectives: ['Correct deficiency without burning crop', 'Restore chlorophyll in new leaves'],
    ipm: ['SPAD or leaf colour chart on youngest fully expanded leaf'],
    cultural: ['Split fertigation doses; avoid single heavy dump in hot sun'],
    nutrition: ['Soil test guided NPK + micronutrients', 'Foliar micronutrients if uptake blocked'],
    biological: [],
    chemical: [
      { activeIngredientClass: 'NPK foliar', notes: 'Jar test before full tank mix' },
      { activeIngredientClass: 'Zn/Mn chelate', notes: 'Only if deficiency confirmed on soil/leaf test' },
    ],
    monitoring: ['D7 new leaf colour', 'D21 SPAD re-check'],
  },
];

/** Ginger scientific knowledge v1 — LR matrix + question bank (expert-governed, not auto-trained). */
export const GINGER_KNOWLEDGE_V1: CropKnowledgePackage = {
  cropType: 'ginger',
  version: '1.0',
  diseaseLabels: [
    'Pyricularia leaf blast',
    'Rhizome rot / Pythium',
    'Thrips',
    'Anthracnose / fungal leaf spot',
    'Nutrient deficiency',
    'Unknown',
  ],
  defaultPriorWeight: {
    'Pyricularia leaf blast': 0.18,
    'Rhizome rot / Pythium': 0.16,
    'Thrips': 0.12,
    'Anthracnose / fungal leaf spot': 0.14,
    'Nutrient deficiency': 0.15,
    Unknown: 0.25,
  },
  likelihoodRatios: [
    { evidenceKey: 'weather:heavy_rain', diseaseLabel: 'Rhizome rot / Pythium', lr: 2.8 },
    { evidenceKey: 'weather:high_humidity', diseaseLabel: 'Pyricularia leaf blast', lr: 2.4 },
    { evidenceKey: 'weather:high_humidity', diseaseLabel: 'Anthracnose / fungal leaf spot', lr: 2.0 },
    { evidenceKey: 'symptom:spindle_lesion', diseaseLabel: 'Pyricularia leaf blast', lr: 3.2 },
    { evidenceKey: 'symptom:grey_center', diseaseLabel: 'Pyricularia leaf blast', lr: 2.6 },
    { evidenceKey: 'symptom:black_dots', diseaseLabel: 'Pyricularia leaf blast', lr: 2.9 },
    { evidenceKey: 'symptom:silver_streak', diseaseLabel: 'Thrips', lr: 3.0 },
    { evidenceKey: 'symptom:soft_rot', diseaseLabel: 'Rhizome rot / Pythium', lr: 3.5 },
    { evidenceKey: 'symptom:yellowing', diseaseLabel: 'Nutrient deficiency', lr: 2.2 },
    { evidenceKey: 'symptom:waterlogged', diseaseLabel: 'Rhizome rot / Pythium', lr: 2.5 },
    { evidenceKey: 'vision:blast', diseaseLabel: 'Pyricularia leaf blast', lr: 2.8 },
    { evidenceKey: 'vision:rot', diseaseLabel: 'Rhizome rot / Pythium', lr: 2.7 },
    { evidenceKey: 'vision:thrips', diseaseLabel: 'Thrips', lr: 2.6 },
    { evidenceKey: 'farmer:black_dots_yes', diseaseLabel: 'Pyricularia leaf blast', lr: 2.8 },
    { evidenceKey: 'farmer:rain_worse_yes', diseaseLabel: 'Pyricularia leaf blast', lr: 2.1 },
    { evidenceKey: 'farmer:rain_worse_yes', diseaseLabel: 'Rhizome rot / Pythium', lr: 2.3 },
    { evidenceKey: 'soil:low_n', diseaseLabel: 'Nutrient deficiency', lr: 2.4 },
    { evidenceKey: 'regional:prior', diseaseLabel: 'Pyricularia leaf blast', lr: 1.4 },
    { evidenceKey: 'context:k_demand_stage', diseaseLabel: 'Nutrient deficiency', lr: 2.8 },
    { evidenceKey: 'context:fertilizer_gap_21d', diseaseLabel: 'Nutrient deficiency', lr: 2.3 },
    { evidenceKey: 'context:prolonged_wet', diseaseLabel: 'Nutrient deficiency', lr: 1.8 },
    { evidenceKey: 'context:prolonged_wet', diseaseLabel: 'Rhizome rot / Pythium', lr: 1.6 },
    { evidenceKey: 'symptom:margin_scorch', diseaseLabel: 'Nutrient deficiency', lr: 2.7 },
    { evidenceKey: 'symptom:margin_scorch', diseaseLabel: 'Pyricularia leaf blast', lr: 0.72 },
    { evidenceKey: 'symptom:no_blast_lesions', diseaseLabel: 'Pyricularia leaf blast', lr: 0.32 },
    { evidenceKey: 'farmer:black_dots_no', diseaseLabel: 'Pyricularia leaf blast', lr: 0.38 },
  ],
  questions: [
    {
      id: 'black_dots_in_lesion',
      text: 'Are black dots visible inside the lesions?',
      answerType: 'yes_no',
      evidenceKeyIfYes: 'farmer:black_dots_yes',
      evidenceKeyIfNo: 'farmer:black_dots_no',
    },
    {
      id: 'symptoms_after_rain',
      text: 'Did symptoms worsen after heavy rain in the last 7 days?',
      answerType: 'yes_no',
      evidenceKeyIfYes: 'farmer:rain_worse_yes',
    },
    {
      id: 'silver_streaks',
      text: 'Do you see silver streaks or scraping marks on leaves?',
      answerType: 'yes_no',
      evidenceKeyIfYes: 'symptom:silver_streak',
    },
    {
      id: 'soft_rhizome',
      text: 'Is the rhizome soft or foul-smelling when cut?',
      answerType: 'yes_no',
      evidenceKeyIfYes: 'symptom:soft_rot',
    },
  ],
  managementRules: GINGER_MANAGEMENT,
  safetyRules: GINGER_SAFETY_RULES,
};
